### ISSUE TITLE
XSS Vulnerability in create.php

### ISSUE THREAD

**Issue by djhayman** [taniarascia/pdo#1]
The file /public/create.php has an XSS vulnerability on line 43:

`<blockquote><?php echo $_POST['firstname']; ?> successfully added.</blockquote>`

The value `$_POST['firstname']` is not being escaped.

Below is a suggested fix:

`<blockquote><?php echo escape($_POST['firstname']); ?> successfully added.</blockquote>`

**Comment by taniarascia** [comment]
Excellent first GitHub issue. The `$_POST` has properly been escaped in the code and article.
