### ISSUE TITLE
XSS Vulnerability in update-single.php

### ISSUE THREAD

**Issue by djhayman** [taniarascia/pdo#2]
The file /public/update-single.php has an XSS vulnerability on line 54:

`<blockquote><?php echo $_POST['firstname']; ?> successfully updated.</blockquote>`

The value `$_POST['firstname']` is not being escaped.

Below is a suggested fix:

`<blockquote><?php echo escape($_POST['firstname']); ?> successfully updated.</blockquote>`

**Comment by taniarascia** [comment]
All set.
