### ISSUE TITLE
XSS Vulnerability in update-single.php

### ISSUE THREAD

**Issue by djhayman** [taniarascia/pdo#3]
The file /public/update-single.php has an XSS vulnerability on line  62:

`<input type="text" name="<?php echo $key; ?>" id="<?php echo $key; ?>" value="<?php echo $value; ?>" <?php echo ($key === 'id' ? 'readonly' : null); ?>>`

The value `$value` is not being escaped.

Below is a suggested fix:

`<input type="text" name="<?php echo $key; ?>" id="<?php echo $key; ?>" value="<?php echo escape($value); ?>" <?php echo ($key === 'id' ? 'readonly' : null); ?>>`

**Comment by taniarascia** [comment]
All set.
