### ISSUE TITLE
SQL Injection Vulnerability in update-single.php

### ISSUE THREAD

**Issue by djhayman** [taniarascia/pdo#4]
The file /public/update-single.php has an SQL injection vulnerability due to the following lines:

```
$items = [];
foreach($_POST as $key => $value) {
  if ($key == 'submit') continue; // ignore submit in $_POST
  $items[] = "$key = :$key";
}
$items = implode(", ", $items);
$sql = sprintf('UPDATE %s SET %s WHERE id = :id', 'users', $items);
```

The vulnerability is present because the `$key` values (coming from `$_POST`) are injected directly into the SQL statement.

A malicious user could post a specially crafted form with a key name (note: key name, not key value) like this:

```
<form id="form" action="pdo/update-single.php" method="post">
    <input name="`id`=`id`;TRUNCATE`users`;--" type="hidden" value="" />

    <input name="submit" type="submit" value="Submit" />
</form>
```

After execution of this line:

```
$sql = sprintf('UPDATE %s SET %s WHERE id = :id', 'users', $items);
```

The `$sql` variable will contain the following value:

```
$sql = 'UPDATE users SET `id`=`id`;TRUNCATE`users`;-- WHERE id = :id';
```

The `UPDATE` portion is essentially a no-op, but it is required so that the overall SQL statement is valid.

The `$statement = $connection->prepare($sql);` line later is protecting against malicious form values, but by this time a malicious form name could have already been injected.

**Comment by taniarascia** [comment]
Excellent point! I will add a note into the article shortly about this type of SQL injection. Thank you for bringing it to my attention.  The code and article has been updated with the following prepared statement:

```php
    $user =[
      // $_POST values
    ];

    $sql = "UPDATE users 
            SET id = :id, 
              firstname = :firstname, 
              lastname = :lastname, 
              email = :email, 
              age = :age, 
              location = :location, 
              date = :date 
            WHERE id = :id";
  
  $statement = $connection->prepare($sql);
  $statement->execute($user);
```

Submitting the aforementioned injection no longer truncates the table.
