### ISSUE TITLE
Doesn't work using PHP 5.3

### ISSUE THREAD

**Issue by alanmead** [taniarascia/pdo#8]
This sample app was extremely helpful to me, but I'm using CentOS 6, which defaults to PHP 5.3.3 and this code doesn't run on 5.3. However, I was able to get it to run correctly. 

For example, you use `$new_user = array(...` to init an array in create.php, which works in 5.3 but you use the new style `$user =[...` to init an array in update-single.php, which doesn't work in 5.3.

Do you want patches? (Or a pull request?)

**Comment by taniarascia** [comment]
PHP 5.3 was deprecated in August 2014, 5 years ago, so I'm not going to make any changes to make this backwards compatible. Anyone who wants to use the code for 5.3 can individually make the necessary changes.
